# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion="[1,)" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

# A URL to refer people to when problems occur with this mod
# issueTrackerURL="" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="alchemyexpanded" #mandatory

# The version number of the mod
version="1.0" #mandatory

# A display name for the mod
displayName="Alchemy Expanded" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
# updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="alchemyexpanded.png" #optional

# A text field displayed in the mod UI
#credits="Art and Code by rose_bushes_, with code snippets taken from GunsWithoutRoses under MIT license." #optional

# A text field displayed in the mod UI
authors="rose_bushes_" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''An addon for Minestuck.'''

# Here's another dependency
[[dependencies.alchemyexpanded]]
    modId="neoforge"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.alchemyexpanded]]
    modId="minestuck"
    type="required"
    versionRange="1.12.2.0"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.alchemyexpanded]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"